server:
  port: 8100

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: false
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driverClassName: oracle.jdbc.OracleDriver
    username: posqr
    password: oracle
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false